server:
  port: 8082

spring:
  application:
    name: sinbi
  profiles:
    active: local,account
  config:
    import: optional:configserver:http://15.164.159.172:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh

