
spring:
  application:
    name: sinbi
  profiles:
    active: deployment,virtualAccount
  config:
    import: optional:configserver:http://15.164.159.172:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh
