spring:
  application:
    name: sinbi
  profiles:
    active: local
  config:
    import: optional:configserver:http://15.164.159.172:8888
  kafka:
    bootstrap-servers: localhost:9092  # Kafka ??? ??
    consumer:
      group-id: virtualAccount  # ??? ?? ID
      auto-offset-reset: earliest   # ??? ?? ?? ?? (earliest, latest ?)
      properties:
        spring.json.trusted.packages: "*"  # JSON ??? ?? ? ??? ???
    topics:  # ?? ?? ??
      first-find-virtual-account: sinbi.firstFindVirtualAccount  # ? ?? ??
      second-find-virtual-account: sinbi.secondFindVirtualAccount  # ? ?? ??
      first-deposit: sinbi.firstDeposit # ? ?? ??
      second-deposit: sinbi.secondDeposit
      find-user-id: sinbi.findUserId
    listener:
      concurrency: 3  # ??? ??? ? (??)
management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8081