spring:
  application:
    name: sinbi
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh
