spring:
  application:
    name: sinbi
  profiles:
    active: local
  config:
    import: optional:configserver:http://15.164.159.172:8888
  data:
    redis:
      port: 6379
      host: localhost

management:
  endpoints:
    web:
      exposure:
        include: refresh